// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asbkbfyymabugonuomrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzYmtiZnl5bWFidWdvbnVvbXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMjgwNjUsImV4cCI6MjA1MTYwNDA2NX0.j3ipg778NwO04F0utpyz-dMtmX6QuPEpY7x0VzbgpK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);